### ISSUE TITLE
The files with the same name and path in arc.nsa and arc.sar

### ISSUE THREAD

**Issue by Dimoks** [matthewn4444/onscripter-plus-android#22]
ONScripter Plus 1.2.4 ignores the files in **arc.nsa** with the same name and path as in **arc.sar**.
For example "image\gameopt\effectok.jpg" in **arc.nsa** are ignored in “Tsukihime Russian Demo”.
PC (ONSlaught):
![20180122t211756_0000163507](https://user-images.githubusercontent.com/3314441/35238692-5037fea8-ffbf-11e7-98c6-8965d0755f07.jpg)
ONScripter Plus:
![screenshot_2018-01-23-02-15-08](https://user-images.githubusercontent.com/3314441/35238741-7d5efe4a-ffbf-11e7-93cc-9a89ec9c0035.png)

**Comment by matthewn4444** [comment]
Moving to engine since engine bug. Please respond and subscribe to issue: https://github.com/matthewn4444/onscripter-engine-android/issues/2

What is missing in this screenshot? I think I did merge sar and nsa together but i can check again (the change was https://github.com/matthewn4444/onscripter-engine-android/commit/5782e200888758dd7210c9cfb819c13d1a11de4b)
